apiVersion: v2
appVersion: 0.0.181-13-27863455-master
description: A Helm chart for Kubernetes
icon: https://rawcdn.githack.com/jenkins-x/jx-docs/e9afbc5c933c8f2d004cb041e2fa33b391a8fd23/static/images/logo/jenkinsx-ico-black.png
name: jxl-boot
version: 0.0.181-13-27863455-master
